language: java
before_install:
- openssl aes-256-cbc -K $encrypted_ba588a873fad_key -iv $encrypted_ba588a873fad_iv
  -in all.gpg.enc -out all.gpg -d
- gpg --import all.gpg
stages:
  - name: ${TRAVIS_TAG}
    if: tag IS present
  - name: build
    if: type = push
jobs:
  include:
    - stage: ${TRAVIS_TAG}
      after_success:
      - mvn deploy -Dgpg.passphrase='${env.KEY_PASSPHRASE}' -Prelease --settings ./travis-maven-settings.xml
    - stage: build
cache:
  directories:
    - $HOME/.m2/repository/
