language: java
after_success:
- echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers><profiles><profile><id>sonatype-oss-release</id><properties><gpg.keyname>E22CF6BD97DF7042</gpg.keyname><gpg.passphrase>\${env.KEY_PASSPHRASE}</gpg.passphrase><gpg.secretKeyring>all.gpg</gpg.secretKeyring></properties></profile></profiles></settings>" > ~/settings.xml
- mvn deploy -Prelease -X --settings ~/settings.xml
dd:
- openssl aes-256-cbc -K $encrypted_ba588a873fad_key -iv $encrypted_ba588a873fad_iv
  -in all.gpg.enc -out all.gpg -d
cache:
  directories:
    - $HOME/.m2/repository/